pipeline{
    agent any
    environment{
        PROJECT_ID = 'flask-app-318214'
        LOCAL_TAG = "flask-app:${env.BUILD_NUMBER}"
        REMOTE_TAG = "eu.gcr.io/$PROJECT_ID/$LOCAL_TAG"
        //SERVICE_ACCOUNT_EMAIL = 'jenkins@avian-scanner-317608.iam.gserviceaccount.com'
        CONTAINER_NAME = 'flask-app'
    }
    stages{
        stage('Checkout'){
            steps{
                git 'https://github.com/vladStepanenko1/flask-app.git'
            }
        }
        stage('Build docker image'){
            steps{
                script{
                    appImage = docker.build(LOCAL_TAG, '-f ./docker/Dockerfile .')
                }
            }
        }
        stage('Test'){
            steps{
                script{
                    appImage.inside{
                        sh 'python tests.py'
                    }
                }
            }
        }
        stage('Push docker image'){
            agent{
                docker{
                    image 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
                }
            }
            steps{
                script{
                    withCredentials([file(credentialsId: 'flask-app-key', variable: 'GC_KEY')]){
                        sh 'cat $GC_KEY | docker login -u _json_key --password-stdin https://eu.gcr.io'
                        sh 'gcloud auth activate-service-account --key-file=$GC_KEY'
                        sh 'gcloud auth configure-docker'
                        echo 'Pushing $LOCAL_TAG image to container registry'
                        sh 'docker tag $LOCAL_TAG $REMOTE_TAG'
                        sh 'docker push $REMOTE_TAG'
                    }
                }
            }
        }
        // stage('Deploy'){
        //     agent{
        //         docker {
        //             image 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
        //         }
        //     }
        //     steps{
        //         withCredentials([file(credentialsId: 'gcp-key', variable: 'GCP_KEY')]){
        //             sh 'gcloud auth activate-service-account $SERVICE_ACCOUNT_EMAIL --key-file=${GCP_KEY} --project=$GCLOUD_PROJECT'
        //             sh 'gcloud compute ssh --project=$GCLOUD_PROJECT --zone=europe-west3-a vladstepanenko1@example-vm --command="docker stop --name $CONTAINER_NAME"'
        //             sh 'gcloud compute ssh --project=$GCLOUD_PROJECT --zone=europe-west3-a vladstepanenko1@example-vm --command="docker rm --name $CONTAINER_NAME"'
        //             sh 'gcloud compute ssh --project=$GCLOUD_PROJECT --zone=europe-west3-a vladstepanenko1@example-vm --command="docker run --name $CONTAINER_NAME -d -p 5001:5000 $REMOTE_TAG"'
        //         }
        //     }
        // }
    }
}